[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Override with: --profile fuzz
[profile.fuzz]
src = "src"
out = "out"
libs = ["lib"]

# Override with: --profile intense
[profile.intense]
src = "src"
out = "out"
libs = ["lib"]

[fuzz]
runs = 10000
